### ISSUE TITLE
Bundling app does not work

### ISSUE THREAD

**Issue by akoenig** [bvic23/babel-plugin-functional-hmr#1]
Thanks for building this plugin. It really helps to overcome the annoying scenario that only classes benefit from hot reloading capabilities.

I identified one problem when bundling the app for Android though. While performing a `cd android && ./gradlew assembleRelease` the build fails with:

```
Loading dependency graph, done.
warning: the transform cache was reset.

SyntaxError: Unexpected token: name (id)

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Removing the plugin configuration in `.babelrc` helps and the build succeeds again.

**Comment by bvic23** [comment]
@akoenig thanks for raising the issue, please try the latest version (1.0.18), hope it works.

**Comment by akoenig** [comment]
@bvic23 Awesome, works like a charm. Thanks for that quick fix!

**Comment by bvic23** [comment]
@akoenig :-)
