### ISSUE TITLE
Error in React Native 0.53

### ISSUE THREAD

**Issue by MrLoh** [bvic23/babel-plugin-functional-hmr#11]
When running in React Native 0.53 this package causes an error `requiring unknown module "react"`. Not sure what could be causing this.

**Comment by Gyran** [comment]
Have you tried to restart your packager with a clear cache?

```
react-native start --reset-cache
```

https://github.com/bvic23/babel-plugin-functional-hmr/issues/9

**Comment by Gyran** [comment]
which version of the plugin are you using?

**Comment by MrLoh** [comment]
the later of the 2 versions.

**Comment by Gyran** [comment]
A fix for React Native 0.52+ landed in 1.0.24 so try to upgrade

**Comment by MrLoh** [comment]
Oh, ok I guess the versions are not visible here on github, I'll try that out

**Comment by Gyran** [comment]
No unfortunately not, you have to look at https://www.npmjs.com/package/babel-plugin-functional-hmr to see the latest released version

**Comment by MrLoh** [comment]
ok, yeah that was the issue. Thanks for the hint, sorry for not checking that first, I just looked at the latest release here on github and assumed I was on the latest version.
