### ISSUE TITLE
Support for higher-order-components such as recompose

### ISSUE THREAD

**Issue by ckknight** [bvic23/babel-plugin-functional-hmr#12]
A pattern that I tend to use is the following:

```js
import React from 'react';
import { withState } from 'recompose'; // or any of the HOCs from recompose

const enhancer = withState('value', 'setValue', 0);
const MyComponent = ({ value, setValue }) => (
  <div>
    <span>Value: {String(value)}</span>
    <button onClick={() => setValue(value + 1)}>Increment</button>
  </div>
);
export default enhancer(MyComponent);
```

Because `MyComponent` is not being `export`ed as a `const` or `default`, it is not being picked up by `babel-plugin-functional-hmr`.

Is there a way I can adjust my pattern or is there something that could be done regarding `babel-plugin-functional-hmr` to get this experience working with HMR?

**Comment by ckknight** [comment]
I am able to work around this rather begrudgingly by having the following lines at the bottom:

```js
const EnhancedMyComponent = enhancer(MyComponent);
export default ({ ...props }) => <EnhancedMyComponent {...props} />;
```

I'd prefer not to have to.

**Comment by bvic23** [comment]
Your special pattern is not supported, feel free to send a PR with some tests and I will merge it ASAP!

**Comment by Gyran** [comment]
We have a branch that supports that pattern (https://github.com/bvic23/babel-plugin-functional-hmr/compare/master...Yepstr:hoc). I'm not sure that it works 100% but it works good enough for us. If anyone want to continue to work on it I'd be glad to help.

**Comment by ckknight** [comment]
@bvic23 My actual code is for `react-native`, I was attempting to provide a quick example.

Here is an equivalent example in `react-native`:

```js
import React from 'react';
import { View, Text, Button } from 'react-native';
import { withState } from 'recompose'; // or any of the HOCs from recompose

const enhancer = withState('value', 'setValue', 0);
const MyComponent = ({ value, setValue }) => (
  <View>
    <Text>Value: {String(value)}</Text>
    <Button onPress={() => setValue(value + 1)}><Text>Increment</Text></Button>
  </View>
);
export default enhancer(MyComponent);
```

**Comment by ckknight** [comment]
@Gyran Thank you, this is working like a dream.
