### ISSUE TITLE
Issue with HMR with fragment syntax

### ISSUE THREAD

**Issue by tylerjbainbridge** [bvic23/babel-plugin-functional-hmr#13]
I believe there is an issue with how this package detects if a function returns JSX. 

HMR does not detect changes on a component that returns a fragment using babel syntax <></>

HMR doesn't see changes here
```jsx
const ExampleScreen = () => (
  <>
    <View style={{ backgroundColor: 'red', height: '100%' }} />
  </>
);
```

This works fine
```jsx
const ExampleScreen = () => (
  <React.Fragment>
    <View style={{ backgroundColor: 'red', height: '100%' }} />
  </React.Fragment>
);
```

**Comment by bvic23** [comment]
Good point! Would you send a PR fixing this please?

**Comment by bvic23** [comment]
Close it due inactivity
