### ISSUE TITLE
Won't work with hooks

### ISSUE THREAD

**Issue by andreasbergqvist** [bvic23/babel-plugin-functional-hmr#17]
Just a notice. Since this is actually transforming functional components to classes (as I understand it). If you try to use hooks in your source they won't work (you will get an "Hooks can only be called inside the body of a function component").

This is ofcourse "by design" when using this plugin.

Maybe update the readme with a notice regarding this so others won't get their hopes up (like me) that you can use functional compoents, hooks AND hot reloading in your React Native apps...

**Comment by bvic23** [comment]
Thanks @andreasbergqvist, I've updated the [README](https://github.com/bvic23/babel-plugin-functional-hmr/blob/master/README.md).

BTW feel free to send PR fixes the hooks issue!
