### ISSUE TITLE
Deprecating the package

### ISSUE THREAD

**Issue by gaearon** [bvic23/babel-plugin-functional-hmr#20]
Hi! Now that React Native 0.61 fixes the problem with Fast Refresh, it would be great if this project could have a loud deprecation notice in README.

The transform it's doing is not safe because it changes functions into classes. It's also making the code slower because the function codepath is more optimized in React.

Thank you!

**Comment by bvic23** [comment]
Hi @gaearon,

Thanks for raising. Consider it done!

Bests,
v

**Comment by gaearon** [comment]
Thanks!!
