### ISSUE TITLE
setup help

### ISSUE THREAD

**Issue by MrLoh** [bvic23/babel-plugin-functional-hmr#5]
I somehow can't get this plugin to work. I'm tryin to use it with storybook. I'm not getting any errors, but the HMR isn't working either. Is there any way to check wether the plugin actually does it's transforms?

**Comment by bvic23** [comment]
Could you attach your `package.json`, `.babelrc` and the functional component you'd like to use in storyboard? Could you also verify that HMR is enabled in the simulators/emulator?

**Comment by MrLoh** [comment]
Hi thanks a lot for the help. So everything is pretty standard: 

package.json
```json
{
   ...
  "dependencies": {
    ...
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "styled-components": "^2.1.1"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^3.2.11",
    "@storybook/addon-links": "^3.2.10",
    "@storybook/react-native": "^3.2.11",
    "babel-eslint": "^7.2.3",
    "babel-plugin-functional-hmr": "^1.0.21",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "lint-staged": "^4.0.3",
    "react-dom": "16.0.0-alpha.12",
    "react-native-dotenv": "^0.1.0",
    "react-native-scripts": "^1.1.0",
    "react-test-renderer": "16.0.0-alpha.12",
    ...
  },
  "rnpm": {
    "assets": [
      "./cinuru-design/assets/fonts/"
    ]
  },
  "lint-staged": {
    "*.js": [
      "prettier --write",
      "git add"
    ]
  }
}
```

.babelrc
```json
{
  "presets": ["babel-preset-react-native-stage-0/decorator-support", "react-native-dotenv"],
  "env": {
    "development": {
      "plugins": ["functional-hmr", "transform-react-jsx-source"]
    }
  }
}

HMR is definitely enabled and it works with classes as well. I'm just having the automatically set up components from storybook. the Welcome is a class and works fine. But the Button is a functional component and it doesn't change.

**Comment by MrLoh** [comment]
Is there any way to see in the react native debugger wether the component actually got transformed?

**Comment by MrLoh** [comment]
Ok, I think I got it to work. The problem is, that editing the `.babelrc` won't actually change the setup, unless you start the packager with `yarn start --reset-cache` to clean the transform cache. Super confusing, cost me several hours.

**Comment by bvic23** [comment]
Sorry for the inconvenience and thanks for getting back. I had a busy week I planned to fix tonight! Anyway I've updated the readme with your finding! Thanks.

**Comment by bvic23** [comment]
I found out why cache reset did not come into my mind: RN packager is so different from React's webpack whenever I have any trouble (warnings, red screens, missing transforms) I immediately run the following script before debugging:

```bash
#!/bin/sh
DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR
rm -rf node_modules/
yarn install
watchman watch-del-all
rm -rf $TMPDIR/react-*
```

**Comment by MrLoh** [comment]
Yes it’s really f* up, so much undeterministic behavior. I really love React Native, but the dev experience is so much worse as compared to web. I’ll copy your script!
